import { fontMontserrat } from "@/fonts";
import CartProvider from "@/context/cart";
import { pageName } from "@/data";
import "@/globals.css";

export const metadata = {
  title: pageName,
  // description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} className="scroll-smooth">
      <body className={`${fontMontserrat.variable} font-montserrat`}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
