import { NextIntlClientProvider, useMessages } from "next-intl";
import { fontMontserrat } from "@/fonts";

import Provider from "@/components/layouts/Provider";
import { pageName } from "@/data";
import "@/globals.css";

export const metadata = {
  title: pageName,
  // description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages();

  return (
    <html lang={locale} className="scroll-smooth">
      <body className={`${fontMontserrat.variable} font-montserrat`}>
        <NextIntlClientProvider
          messages={messages}
          timeZone="America/Mexico_City"
          now={new Date()}
          locale={locale}
        >
          <Provider>{children}</Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
